# Generated by Django 6.0.1 on 2026-02-20 09:00

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True, validators=[users.validators.UsernameValidator(), django.core.validators.MinLengthValidator(3)])),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(validators=[users.validators.PhoneNumberValidator(10)])),
                ('email', models.EmailField(max_length=254, validators=[users.validators.EmailValidator()])),
            ],
        ),
    ]
