# Generated by Django 6.0.1 on 2026-01-24 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reader',
            new_name='User',
        ),
    ]
