# Generated by Django 6.0.1 on 2026-02-23 21:07

from django.db import migrations

users = [
        {
            "username": "eldrin_shadowmere",
            "email": "eldrin@hotmail.com",
            "first_name": "Eldrin",
            "last_name": "Shadowmere",
            "phone_number": "0888888888",
        },
        {
            "username": "lyra_moonwhisper",
            "email": "lyra@hotmail.com",
            "first_name": "Lyra",
            "last_name": "Moonwhisper",
            "phone_number": "0888888888",
        },
        {
            "username": "theron_ashveil",
            "email": "theron@gmail.com",
            "first_name": "Theron",
            "last_name": "Ashveil",
            "phone_number": "0888888888",
        },
        {
            "username": "seraphine_duskwood",
            "email": "seraphine@abv.bg",
            "first_name": "Seraphine",
            "last_name": "Duskwood",
            "phone_number": "0888888888",
        },
        {
            "username": "corvus_nighthollow",
            "email": "corvus@gmail.com",
            "first_name": "Corvus",
            "last_name": "Nighthollow",
            "phone_number": "0888888888",
        },
    ]
def populate_users(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user_data in users:
        User.objects.get_or_create(
            username=user_data["username"],
            first_name=user_data["first_name"],
            last_name=user_data["last_name"],
            phone_number=user_data["phone_number"],
            email=user_data["email"],
        )

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_users),
    ]
