# Generated by Django 6.0.1 on 2026-02-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_reader_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subscription',
        ),
    ]
