# Generated by Django 6.0.1 on 2026-04-05 09:56

import users.validators
from django.db import migrations, models
from django.db.models import Q


def clear_null_phone_numbers(apps, schema_editor):
    # Replace NULL/empty phone numbers with unique placeholders before making
    # the field non-nullable and unique.
    User = apps.get_model('users', 'User')
    users_without_phone = User.objects.filter(
        Q(phone_number__isnull=True) | Q(phone_number='')
    )
    for i, user in enumerate(users_without_phone):
        user.phone_number = f'0000000{i:03d}'
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RunPython(clear_null_phone_numbers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(unique=True, validators=[users.validators.PhoneNumberValidator(10)]),
        ),
    ]
