# Generated by Django 6.0.1 on 2026-02-18 08:54

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_email_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(validators=[users.validators.PhoneNumberValidator(10)]),
        ),
    ]
