# Generated by Django 6.0.1 on 2026-02-20 09:00

import django.db.models.deletion
import grimoire.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grimoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type_of_story', models.CharField(choices=[('SPELL', 'Spell'), ('POTION', 'Potion Recipe'), ('PROPHECY', 'Prophecy'), ('CURSE', 'Curse'), ('LEGEND', 'Legend'), ('MYTH', 'Myth'), ('FAIRYTALE', 'Fairy Tale'), ('RITUAL', 'Ritual'), ('ALCHEMY', 'Alchemy Notes'), ('CHRONICLE', 'Chronicle'), ('DREAM', 'Dream Vision'), ('SONG', 'Magical Song'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='grimoire_images/', validators=[grimoire.validators.FileSizeValidator(5)])),
                ('magician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grimoires', to='users.user')),
            ],
        ),
    ]
