# Generated by Django 6.0.1 on 2026-02-23 20:55

from django.db import migrations

grimoires = [
    {
        "body": """In the silver light of the full moon, gather three sprigs of moonflower and crush them between stones that have never touched iron. 
Pour the morning dew collected from spider webs into a obsidian bowl, and whisper the words of unbinding three times. 
The water will turn the color of starlight. Add a single hair from a sleeping dreamer and stir counterclockwise until the liquid thickens. 
Speak the name of what you wish to forget, and drink before the moon sets. 
Warning: This spell may not be reversed. What is forgotten is gone forever, carried away by the river of dreams.""",
        "type_of_story": "SPELL",
        "image":"image1",
    "magician_username": "eldrin_shadowmere",
    },
    {
        "body": """Year 1247 of the Third Age. I have finally completed my research on dragon fire and its alchemical properties.
The scales of the Wyrm, when ground to powder and mixed with lava from the Volcanic Peaks of Ashmore, produce a compound unlike anything seen before.
It does not burn — it transforms. Wood becomes crystal. Water becomes flame. Flesh becomes... something else.
I have tested it on three subjects. Two did not survive. The third has not spoken since, but his eyes glow faintly in the dark.
I must continue. The Potion of Dragon Breath is within reach. The Council must never know of these experiments.""",
        "type_of_story": "ALCHEMY",
        "image":"image3",
        "magician_username": "lyra_moonwhisper",

    },
    {
        "body": """When the last star falls into the sea and the moon forgets her own name,
a child born of shadow and light shall rise from the Valley of Echoes.
She will carry a wound that does not bleed and a sword that does not cut,
and the ancient ones will bow not from fear, but from recognition.
Three kingdoms will offer their crowns. She will refuse them all.
Her reign will not be one of land or gold, but of memory —
she will restore what was stolen from the world before the first winter,
and those who wronged the forgotten ones shall finally face their reckoning.
This was seen in the flame of the eternal candle on the night of the blood eclipse,
witnessed by seven blind seers who wept tears of gold.""",
        "type_of_story": "PROPHECY",
        "image":"image2",
"magician_username": "corvus_nighthollow",

    },
]

def create_grimoires(apps, schema_editor):
    Grimoire = apps.get_model('grimoire', 'Grimoire')
    User = apps.get_model('users', 'User')

    for grimoire in grimoires:
        user = User.objects.filter(username=grimoire["magician_username"]).first()
        if user:
            Grimoire.objects.create(
                body=grimoire["body"],
                type_of_story=grimoire["type_of_story"],
                magician=user,
            )
class Migration(migrations.Migration):

    dependencies = [
        ('grimoire', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_grimoires),
    ]
