# Generated by Django 6.0.1 on 2026-02-19 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grimoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grimoire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grimoire_images/'),
        ),
    ]
