# Generated by Django 6.0.1 on 2026-02-19 13:51

import grimoire.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grimoire', '0002_grimoire_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grimoire',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='grimoire_images/', validators=[grimoire.validators.FileSizeValidator(5)]),
        ),
    ]
