# Generated by Django 6.0.1 on 2026-04-07 04:52

import grimoire.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grimoire', '0002_populate_grimoires_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grimoire',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='grimoire_images/', validators=[grimoire.validators.FileSizeValidator(5)]),
        ),
    ]
