# Generated by Django 6.0.1 on 2026-01-25 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons', '0001_initial'),
        ('users', '0002_rename_reader_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='rider',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
