# Generated by Django 6.0.1 on 2026-01-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dragons', '0002_alter_dragon_rider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dragon',
            name='photo',
            field=models.CharField(max_length=200),
        ),
    ]
