# Generated by Django 6.0.1 on 2026-01-12 20:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('genre', models.TextField(choices=[('FANTASY', 'Fantasy'), ('NOVEL', 'Novel'), ('SCIENCE_FICTION', 'Science Fiction'), ('THRILLER', 'Thriller'), ('CRIME', 'Crime'), ('ROMANCE', 'Romance'), ('HORROR', 'Horror'), ('MYSTERY', 'Mystery'), ('DRAMA', 'Drama'), ('BIOGRAPHY_MEMOIR', 'Biography Memoir'), ('SELF_IMPROVEMENT', 'Self Improvement'), ('BULGARIAN_CLASSICS', 'Bulgarian Classics'), ('POETRY', 'Poetry'), ('LGBT_LITERATURE', 'LGBT Literature'), ('TEXTBOOK', 'Textbook'), ('ESOTERIC', 'Esoteric'), ('COOKBOOKS', 'Cookbooks'), ('ADVENTURE', 'Adventure'), ('SHORT_STORIES', 'Short Stories'), ('ANTHOLOGY', 'Anthology'), ('POPULAR_SCIENCE', 'Popular Science'), ('NONE', 'None')], default='NONE')),
                ('name_of_series', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('subscription', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Borrowed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reader')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.catalog')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.reader')),
            ],
        ),
    ]
