# Generated by Django 6.0.1 on 2026-02-15 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
