# Generated by Django 6.0.1 on 2026-02-20 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('circulation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrowed',
            old_name='reader',
            new_name='magician',
        ),
    ]
