POTION_RECIPES = {
    ("lavender", "milk", "feather"): "Potion of Sweet Dreams",
    ("mint", "water", "crystal"): "Potion of Healing",
    ("sage", "water", "pearl"): "Potion of Clarity",
    ("chamomile", "honey", "dust"): "Potion of Calm Mind",
    ("aloe", "water", "ice_shard"): "Potion of Cooling Skin",
    ("nightshade", "oil", "shadow_dust"): "Potion of Invisibility",
    ("sunflower", "alcohol", "gold_flake"): "Potion of Radiance",
    ("lotus", "water", "moonstone"): "Potion of Water Breathing",
    ("ginger_root", "fire_water", "ash"): "Potion of Fire Resistance",
    ("blue_orchid", "ether", "butterfly_wing"): "Potion of Levitation",
    ("thorn_leaf", "blood", "iron"): "Potion of Strength",
    ("wolf_fang", "oil", "bone_fragment"): "Potion of Rage",
    ("frost_berry", "ice_water", "silver"): "Potion of Frost Armor",
    ("ember_leaf", "alcohol", "dragon_scale"): "Potion of Flame Aura",
    ("nettle", "vinegar", "spider_silk"): "Potion of Poison Touch",
    ("moonflower", "dew", "stardust"): "Potion of Time Slow",
    ("black_rose", "ink", "crow_feather"): "Potion of Shadow Walk",
    ("ghost_mushroom", "fog", "spirit_essence"): "Potion of Spirit Form",
    ("crystal_rose", "holy_water", "opal"): "Potion of Purification",
    ("mandrake", "elixir", "ancient_coin"): "Potion of Memory Recall",
    ("void_root", "tar", "obsidian"): "Potion of Darkness",
    ("blood_lily", "blood", "heart_fragment"): "Potion of Life Drain",
    ("wyrm_scale", "lava", "ruby"): "Potion of Dragon Breath",
    ("time_sand", "mercury", "clock_gear"): "Potion of Time Reversal",
    ("star_tear", "liquid_light", "halo_fragment"): "Potion of Ascension",
}
FAIL_POTIONS = [
    "Potion of Exploding Frogs 🐸💥",
    "Potion of Endless Sneezing 🤧",
    "Potion of Pink Smoke 💨",
    "Potion of Hair Growth (Everywhere)",
    "Potion of Temporary Chicken Language 🐔",
    "Potion of Uncontrollable Dancing 💃",
    "Potion of Invisible Socks",
    "Potion of Loud Thoughts 🔊",
    "Potion of Gravity Confusion",
    "Potion of Beard Multiplication 🧔🧔🧔",
]

HERB_CHOICES = [
    ("lavender", "Lavender"),
    ("mint", "Mint"),
    ("sage", "Silver Sage"),
    ("chamomile", "Golden Chamomile"),
    ("aloe", "Aloe Vera"),
    ("nightshade", "Nightshade"),
    ("sunflower", "Sunflower"),
    ("lotus", "Blue Lotus"),
    ("ginger_root", "Fire Ginger Root"),
    ("blue_orchid", "Blue Orchid"),
    ("thorn_leaf", "Thorn Leaf"),
    ("wolf_fang", "Wolf Fang"),
    ("frost_berry", "Frost Berry"),
    ("ember_leaf", "Ember Leaf"),
    ("nettle", "Nettle"),
    ("moonflower", "Moonflower"),
    ("black_rose", "Black Rose"),
    ("ghost_mushroom", "Ghost Mushroom"),
    ("crystal_rose", "Crystal Rose"),
    ("mandrake", "Mandrake Root"),
    ("void_root", "Void Root"),
    ("blood_lily", "Blood Lily"),
    ("time_sand", "Time Sand"),
    ("star_tear", "Star Tear"),
    ("wyrm_scale", "Wyrm Scale"),
]
LIQUID_CHOICES = [
    ("milk", "Moon Milk"),
    ("water", "Spring Water"),
    ("honey", "Honey Syrup"),
    ("ink", "Octopus Ink"),
    ("oil", "Herbal Oil"),
    ("alcohol", "Dwarven Alcohol"),
    ("blood", "Beast Blood"),
    ("ice_water", "Glacial Water"),
    ("fire_water", "Fire Water"),
    ("dew", "Morning Dew"),
    ("fog", "Captured Fog"),
    ("holy_water", "Holy Water"),
    ("elixir", "Ancient Elixir"),
    ("tar", "Black Tar"),
    ("lava", "Liquid Lava"),
    ("mercury", "Mercury"),
    ("liquid_light", "Liquid Light"),
    ("vinegar", "Sharp Vinegar"),
    ("ice_shard", "Ice Shard"),
    ("ether", "Ether"),
]

ITEM_CHOICES = [
    ("feather", "Phoenix Feather"),
    ("crystal", "Magic Crystal"),
    ("pearl", "Pearl"),
    ("dust", "Fairy Dust"),
    ("shadow_dust", "Shadow Dust"),
    ("gold_flake", "Gold Flake"),
    ("ash", "Sacred Ash"),
    ("butterfly_wing", "Butterfly Wing"),
    ("iron", "Iron Shard"),
    ("bone_fragment", "Bone Fragment"),
    ("silver", "Silver Fragment"),
    ("spider_silk", "Spider Silk"),
    ("stardust", "Stardust"),
    ("crow_feather", "Crow Feather"),
    ("spirit_essence", "Spirit Essence"),
    ("opal", "Opal Gem"),
    ("ancient_coin", "Ancient Coin"),
    ("obsidian", "Obsidian"),
    ("heart_fragment", "Heart Fragment"),
    ("ruby", "Ruby"),
    ("dragon_scale", "Dragon Scale"),
    ("clock_gear", "Clock Gear"),
    ("halo_fragment", "Halo Fragment"),
    ("moonstone", "Moonstone"),
    ("ice_shard", "Ice Shard"),
]


HERB_DICT = dict(HERB_CHOICES)
LIQUID_DICT = dict(LIQUID_CHOICES)
ITEM_DICT = dict(ITEM_CHOICES)