# Generated by Django 6.0.1 on 2026-02-20 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecretPotions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potion', models.CharField(max_length=100)),
                ('herb', models.CharField(max_length=100)),
                ('liquid', models.CharField(max_length=100)),
                ('items', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Potion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('magician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='potions', to='users.user')),
            ],
        ),
    ]
