# Generated by Django 6.0.1 on 2026-02-19 22:13

from django.db import migrations
potions = [
    {"potion": "Potion of Sweet Dreams", "herb": "lavender", "liquid": "milk", "items": "feather"},
    {"potion": "Potion of Healing", "herb": "mint", "liquid": "water", "items": "crystal"},
    {"potion": "Potion of Clarity", "herb": "sage", "liquid": "water", "items": "pearl"},
    {"potion": "Potion of Calm Mind", "herb": "chamomile", "liquid": "honey", "items": "dust"},
    {"potion": "Potion of Cooling Skin", "herb": "aloe", "liquid": "water", "items": "ice_shard"},        # fixed
    {"potion": "Potion of Invisibility", "herb": "nightshade", "liquid": "oil", "items": "shadow_dust"},
    {"potion": "Potion of Radiance", "herb": "sunflower", "liquid": "alcohol", "items": "gold_flake"},
    {"potion": "Potion of Water Breathing", "herb": "lotus", "liquid": "water", "items": "moonstone"},    # fixed
    {"potion": "Potion of Fire Resistance", "herb": "ginger_root", "liquid": "fire_water", "items": "ash"},
    {"potion": "Potion of Levitation", "herb": "blue_orchid", "liquid": "ether", "items": "butterfly_wing"},  # fixed
    {"potion": "Potion of Strength", "herb": "thorn_leaf", "liquid": "blood", "items": "iron"},
    {"potion": "Potion of Rage", "herb": "wolf_fang", "liquid": "oil", "items": "bone_fragment"},         # fixed
    {"potion": "Potion of Frost Armor", "herb": "frost_berry", "liquid": "ice_water", "items": "silver"}, # fixed
    {"potion": "Potion of Flame Aura", "herb": "ember_leaf", "liquid": "alcohol", "items": "dragon_scale"}, # fixed
    {"potion": "Potion of Poison Touch", "herb": "nettle", "liquid": "vinegar", "items": "spider_silk"},  # fixed
    {"potion": "Potion of Time Slow", "herb": "moonflower", "liquid": "dew", "items": "stardust"},
    {"potion": "Potion of Shadow Walk", "herb": "black_rose", "liquid": "ink", "items": "crow_feather"},
    {"potion": "Potion of Spirit Form", "herb": "ghost_mushroom", "liquid": "fog", "items": "spirit_essence"},
    {"potion": "Potion of Purification", "herb": "crystal_rose", "liquid": "holy_water", "items": "opal"}, # fixed
    {"potion": "Potion of Memory Recall", "herb": "mandrake", "liquid": "elixir", "items": "ancient_coin"},
    {"potion": "Potion of Darkness", "herb": "void_root", "liquid": "tar", "items": "obsidian"},
    {"potion": "Potion of Life Drain", "herb": "blood_lily", "liquid": "blood", "items": "heart_fragment"},
    {"potion": "Potion of Dragon Breath", "herb": "wyrm_scale", "liquid": "lava", "items": "ruby"},       # fixed
    {"potion": "Potion of Time Reversal", "herb": "time_sand", "liquid": "mercury", "items": "clock_gear"}, # fixed
    {"potion": "Potion of Ascension", "herb": "star_tear", "liquid": "liquid_light", "items": "halo_fragment"}, # fixed
]
def populate_potions_model(apps, schema_editor):
    SecretPotions = apps.get_model("potions", "SecretPotions")
    for potion in potions:

        SecretPotions.objects.create(
            potion=potion["potion"],
            herb=potion["herb"],
            liquid=potion["liquid"],
            items=potion["items"],
        )

def reverse_populate_potions_model(apps, schema_editor):
    SecretPotions = apps.get_model("potions", "SecretPotions")
    SecretPotions.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('potions', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_potions_model, reverse_populate_potions_model),
    ]
